import {
  Coffee,
  Bed,
  Dumbbell,
  Moon,
  BookOpen,
  Star,
  Heart,
  BookText,
  Footprints,
  Leaf,
  Apple,
  Droplet,
  Flame,
  Sun,
  Cloud,
  Music,
  Pencil,
  Palette,
  Camera,
  Headphones,
  Mic,
  MessageCircle,
  Users,
  PhoneOff,
  Smile,
  Briefcase,
  Wallet,
  PiggyBank,
  Compass,
  Map,
  TreePine,
  Flower2,
  Bike,
  type LucideIcon,
} from 'lucide-react'
import type { IconId } from './types'

export const ICON_MAP: Record<IconId, LucideIcon> = {
  leaf: Leaf,
  coffee: Coffee,
  bed: Bed,
  dumbbell: Dumbbell,
  moon: Moon,
  book: BookOpen,
  star: Star,
  heart: Heart,
  books: BookText,
  runner: Footprints,
  apple: Apple,
  droplet: Droplet,
  flame: Flame,
  sun: Sun,
  cloud: Cloud,
  music: Music,
  pencil: Pencil,
  palette: Palette,
  camera: Camera,
  headphones: Headphones,
  mic: Mic,
  message: MessageCircle,
  users: Users,
  'phone-off': PhoneOff,
  smile: Smile,
  briefcase: Briefcase,
  wallet: Wallet,
  piggy: PiggyBank,
  compass: Compass,
  map: Map,
  tree: TreePine,
  flower: Flower2,
  bike: Bike,
}